- hosts: all
  tasks:
  - apt: update_cache=yes
    sudo: yes

  - name: ensure pip is at the latest version
    apt: name=python-pip state=present
    sudo: yes

  - name: install git
    apt: name=git state=present
    sudo: yes

  - name: install mplayer
    apt: name=mplayer state=present
    sudo: yes

  - name: install python
    apt: name=python2.7-dev state=present
    sudo: yes

  - name: install build-essential
    apt: name=build-essential state=present
    sudo: yes

  - name: install freetype
    apt: name=libfreetype6-dev state=present
    sudo: yes

  - name: install png
    apt: name=libpng-dev state=present
    sudo: yes

  - name: install gfortran
    apt: name=gfortran state=present
    sudo: yes

  - name: install libopenblas-dev
    apt: name=libopenblas-dev state=present
    sudo: yes

  - name: install liblapack-dev
    apt: name=liblapack-dev state=present
    sudo: yes

  - name: install numpy
    pip: name=numpy
    sudo: yes

  - name: install scipy
    pip: name=scipy
    sudo: yes

  - name: install distribute
    pip: name=distribute state=latest
    sudo: yes

  - name: install matplotlib
    pip: name=matplotlib
    sudo: yes

  - name: install dexy
    pip: name=dexy
    sudo: yes

  - name: install ipython
    pip: name=ipython
    sudo: yes

  - name: install SimpleITK
    easy_install: name=SimpleITK
    sudo: yes

  - name: install git
    apt: name=git state=latest
    sudo: yes

  - name: install vim
    apt: name=vim state=latest
    sudo: yes

  - name: install emacs
    apt: name=emacs state=latest
    sudo: yes

  - name: install python-nose
    pip: name=nose
    sudo: yes
